<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php

    echo $playlist->getTitle();

    foreach ($songs as $song) {

        if(in_array($song, $playlist->getSongs())){
            $carita = "💔";
        } else {
            $carita = "❤";
        }

    echo $song->getTitle().' <a href="index.php?link=song&likeSong=1&addPlay=1&idSong='.$song->getId().'&idPlaylist='.$playlist->getId().'">'.$carita.'</a> ';
    echo "<br>" ;
    }

    echo '<a href="index.php?link=song&atras=1">Atras🔙</a>';

    ?>
    
</body>
</html>