<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    echo '<div class="div1">
        <form class="form" action="index.php?link=user" method="POST">
            <label for="username" class="form-label">Nombre Usuario</label>
            <input type="text" class="form-control" name="name" required />

            <label for="password" class="form-label">Contraseña</label>
            <input type="password" class="form-control" name="password" required />
            <input type="submit" name="registrarse" value="registrarse">
        </form>
    </div>';
    ?>
</body>
<style>
.div1 {
    height: 100vh;
    min-height: 100vh;
    border: 1px solid black;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    gap: 20px;
}

form {
    display: flex;
    flex-direction: column;
}

form input {
    margin-bottom: 20px;
}
body {
 margin: 0px ;
}
*{
    box-sizing: border-box;
}
</style>

</html>