<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="index.php?link=song&addPlaylist&play"></a>
    <h2>Ver mis Listas de Saltify</h2>
    <?php
    echo '<span>  </span>';
    echo '<a href="index.php?link=playlist&atras=1">Atras🔙</a> <br><br>';

           echo ' <a href="index.php?link=song&addPlay=1&idPlaylist='.$playlist->getId().'">'.$playlist->getTitle().'</a>';
           echo '<br>';
           
           if (!empty($songs)) {
            echo "<br>" ;
            
            foreach ($songs as $song) {
                    echo $song->getTitle().", ".$song->getAuthor().", ".$song->getDuration()."minutos";
                    echo "<br>" ;
                }
            }
    
    
    ?>

</body>
</html>