<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="index.php?link=song&addPlaylist&play"></a>
    <h2>Ver mis Listas de Saltify</h2>
    <?php
    echo '<span>  </span>';
    echo '<a href="index.php?link=playlist&atras=1">Atras🔙</a> <br><br>';

        foreach ($playlists as $playlist) {
           echo ' <a href="index.php?link=song&addPlay=1&idPlaylist='.$playlist->getId().'">'.$playlist->getTitle().'</a>';
           echo '';
           echo '<br>';
           echo '<a href="index.php?link=playlist&verLista=1&idPlaylist='.$playlist->getId().'">Mostrar Canciones</a>';
           echo '<br>';
           echo '<br>';
           
        }
    
    
    ?>

</body>
</html>